---
- hosts: all
  become: true
  tasks:
    - name: Make sure we can connect
      ping:
    - name: Add the ondrej PHP PPA
      apt_repository: repo='ppa:ondrej/php'
    - name: Update the apt cache
      apt: update_cache=yes cache_valid_time=3600
    - name: Install PHP
      apt: 
        name: 
        - php
        - php-fpm
        - php-mysql
        - php-xml
        state: present
    - name: Remove apache2
      apt: name=apache2 state=absent
    - name: Install MySQL and python mysql
      apt: 
        name:
        - mysql-server-5.7 
        - python-mysqldb
    - name: Generate new root password
      command: openssl rand -hex 7 creates=/root/.my.cnf
      register: mysql_new_root_pass
    - debug: 
        msg: "New root password is {{ mysql_new_root_pass.stdout }}"
      when: mysql_new_root_pass.changed
    - debug: 
        msg: "No change to root password"
      when: not mysql_new_root_pass.changed
    - name: Remove anonymous users
      community.mysql.mysql_user: name="" state=absent
      when: mysql_new_root_pass.changed
    - name: Remove test database
      community.mysql.mysql_db: name=test state=absent
      when: mysql_new_root_pass.changed
    - name: Update root password
      community.mysql.mysql_user: 
        name: root 
        host: |
          "{{ ansible_hostname }}",
          127.0.0.1,
          ::1,
          localhost
        password: "{{mysql_new_root_pass.stdout}}"
      when: mysql_new_root_pass.changed
    - name: Output new root password
      debug: 
        msg: "New root password is {{mysql_new_root_pass.stdout}}"
      when: mysql_new_root_pass.changed
    - name: Create my.cnf
      template: 
        src: templates/mysql/my.cnf
        dest: /root/.my.cnf
      when: mysql_new_root_pass.changed
    - name: Install nginx
      apt: name=nginx state=present
    - name: Start nginx
      service: name=nginx state=started